name: Build and Publish Docker

on:
  push:
    branches:
      - master

jobs:
  build_9_2_0:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master

    - name: Publish to Registry
      uses: elgohr/Publish-Docker-Github-Action@master
      env:
        BUILD_DATE: $(date -u +"%Y-%m-%dT%H:%M:%SZ")
        VCS_URL: $(git config --get remote.origin.url)
        VCS_REF: $(git rev-parse --short HEAD)
        GCC_VERSION: 9.2.0
      with:
        name: leavesask/gcc
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        buildargs: GCC_VERSION,BUILD_DATE,VCS_URL,VCS_REF
        buildoptions: "--compress"
        tags: "latest,9.2.0"

  build_8_3_0:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master

    - name: Publish to Registry
      uses: elgohr/Publish-Docker-Github-Action@master
      env:
        BUILD_DATE: $(date -u +"%Y-%m-%dT%H:%M:%SZ")
        VCS_URL: $(git config --get remote.origin.url)
        VCS_REF: $(git rev-parse --short HEAD)
        GCC_VERSION: 8.3.0
      with:
        name: leavesask/gcc
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        buildargs: GCC_VERSION,BUILD_DATE,VCS_URL,VCS_REF
        buildoptions: "--compress"
        tags: "8.3.0"

  build_7_3_0:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master

    - name: Publish to Registry
      uses: elgohr/Publish-Docker-Github-Action@master
      env:
        BUILD_DATE: $(date -u +"%Y-%m-%dT%H:%M:%SZ")
        VCS_URL: $(git config --get remote.origin.url)
        VCS_REF: $(git rev-parse --short HEAD)
        GCC_VERSION: 7.3.0
      with:
        name: leavesask/gcc
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        buildargs: GCC_VERSION,BUILD_DATE,VCS_URL,VCS_REF
        buildoptions: "--compress"
        tags: "7.3.0"

  build_5_5_0:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master

    - name: Publish to Registry
      uses: elgohr/Publish-Docker-Github-Action@master
      env:
        BUILD_DATE: $(date -u +"%Y-%m-%dT%H:%M:%SZ")
        VCS_URL: $(git config --get remote.origin.url)
        VCS_REF: $(git rev-parse --short HEAD)
        GCC_VERSION: 5.5.0
      with:
        name: leavesask/gcc
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        buildargs: GCC_VERSION,BUILD_DATE,VCS_URL,VCS_REF
        buildoptions: "--compress"
        tags: "5.5.0"
